---
sort: sum                      # max|min|avg|sum|count|uri|method|max-body|min-body|avg-body|sum-body|p1|p50|p99|stddev
reverse: true                   # boolean
query_string: true              # boolean
output: count,5xx,4xx,method,uri,min,max,sum,avg,p99                    # string(comma separated)

# 必ず`^`と`$`を使った完全一致の記述を行うこと
matching_groups:            # array
  - ^/transactions/\d+\.png$
  - ^/upload/[a-zA-Z0-9]+\.jpg$     
  - ^/users/\d+\.json$
  - ^/new_items/\d+\.json$
  # クエリパラメータを加味する
  - ^/users/transactions\.json\?created_at=\d+&item_id=\d+$
  - ^/users/\d+\.json\?created_at=\d+&item_id=\d+$
  - ^/new_items/\d+\.json\?created_at=\d+&item_id=\d+$
  - ^/new_items\.json\?created_at=\d+&item_id=\d+$
  - ^/items/\d+\.json$ 
