@startuml
entity configs {
  *name : VARCHAR(191)
  --
  val : VARCHAR(255)
}

entity users {
  *id : BIGINT
  --
  account_name : VARCHAR(128)
  hashed_password : VARBINARY(191)
  address : VARCHAR(191)
  num_sell_items : INT UNSIGNED
  last_bump : DATETIME
  created_at : DATETIME
}

entity items {
  *id : BIGINT
  --
  seller_id : BIGINT
  buyer_id : BIGINT
  status : ENUM('on_sale', 'trading', 'sold_out', 'stop', 'cancel')
  name : VARCHAR(191)
  price : INT UNSIGNED
  description : TEXT
  image_name : VARCHAR(191)
  category_id : INT UNSIGNED
  created_at : DATETIME
  updated_at : DATETIME
}

entity transaction_evidences {
  *id : BIGINT
  --
  seller_id : BIGINT
  buyer_id : BIGINT
  status : ENUM('wait_shipping', 'wait_done', 'done')
  item_id : BIGINT
  item_name : VARCHAR(191)
  item_price : INT UNSIGNED
  item_description : TEXT
  item_category_id : INT UNSIGNED
  item_root_category_id : INT UNSIGNED
  created_at : DATETIME
  updated_at : DATETIME
}

entity shippings {
  *transaction_evidence_id : BIGINT
  --
  status : ENUM('initial', 'wait_pickup', 'shipping', 'done')
  item_name : VARCHAR(191)
  item_id : BIGINT
  reserve_id : VARCHAR(191)
  reserve_time : BIGINT
  to_address : VARCHAR(191)
  to_name : VARCHAR(191)
  from_address : VARCHAR(191)
  from_name : VARCHAR(191)
  img_binary : MEDIUMBLOB
  created_at : DATETIME
  updated_at : DATETIME
}

entity categories {
  *id : INT UNSIGNED
  --
  parent_id : INT UNSIGNED
  category_name : VARCHAR(191)
}

users ||--o{ items : "seller_id"
users ||--o{ items : "buyer_id"
items ||--o{ transaction_evidences : "item_id"
items ||--o{ shippings : "item_id"
transaction_evidences ||--o{ shippings : "transaction_evidence_id"
categories ||--o{ items : "category_id"
categories ||--o{ transaction_evidences : "item_category_id"
categories ||--o{ transaction_evidences : "item_root_category_id"
categories ||--o{ categories : "parent_id"

@enduml
